#Creates Virtual Private Gateway and attaches to VPC.
AWSTemplateFormatVersion: '2010-09-09'
Description: Virtual Private Gateway and attachment to VPC

Parameters:
  VpcId:
    Type: String
    Description: VPC ID to attach VGW

Resources:
  VirtualPrivateGateway:
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: SecureHybridVPGW

  AttachVGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      VpnGatewayId: !Ref VirtualPrivateGateway

Outputs:
  VirtualPrivateGatewayId:
    Description: VGW ID
    Value: !Ref VirtualPrivateGateway

    #Deploy virtual-private-gateway.yaml to create and attach VGW:
    aws cloudformation deploy --template-file virtual-private-gateway.yaml --stack-name VirtualPrivateGateway \
  --parameter-overrides VpcId=<VPC_ID> \
  --capabilities CAPABILITY_NAMED_IAM
